// ACTION TYPE
// User Details action tppe
export const USER_DETAILS_HAS_ERROR = "USER_DETAILS_HAS_ERROR";
export const USER_DETAILS_IS_LOADING = "USER_DETAILS_IS_LOADING";
export const FETCH_USER_DETAILS_SUCCESS = "FETCH_USER_DETAILS_SUCCESS";

// User Repos action tppe
export const USER_REPOS_IS_LOADING = "USER_REPOS_IS_LOADING";
export const USER_REPOS_HAS_ERROR = "USER_REPOS_HAS_ERROR";
export const FETCH_USER_REPOS_SUCCESS = "FETCH_USER_REPOS_SUCCESS";
